version: '3.3'

services:
  nginx:
    image: nginx:1.19.6
    ports:
      - '80:80'
    volumes:
      - ./nginx/etc.nginx.nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc.nginx.templates.default.conf.template:/etc/nginx/templates/default.conf.template

  web1:
    build:
      context: pyweb
    volumes:
      - ./web1:/app
    ports:
      - '8000:8000'

  web2:
    build:
      context: pyweb
    volumes:
      - ./web2:/app
    ports:
      - '9000:8000'
