version: '3.3'

services:
  nginx:
    image: nginx:1.19.6
    ports:
      - '80:80'
    volumes:
      - ./web3:/app
      - ./nginx/etc.nginx.nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc.nginx.templates.default.conf.template:/etc/nginx/templates/default.conf.template

  web1:
    build:
      context: pyweb
    volumes:
      - ./web1:/app
    ports:
      - '3000:8000'

  web2:
    build:
      context: pyweb
    volumes:
      - ./web2:/app
    ports:
      - '4000:8000'

  web3:
    build:
      context: phpfpm
    volumes:
      - ./web3:/app
    ports:
      - '5000:9000'

  # web4:
  #   build:
  #     context: phpfpm
  #   volumes:
  #     - ./web4:/app
  #   ports:
  #     - '6000:8000'
